"""add shipping_areas and postcode_areas tables

Revision ID: 1703c1c0b966
Revises: 6ac56aaceb5c
Create Date: 2026-07-12 17:52:28.243571

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1703c1c0b966"
down_revision: str | Sequence[str] | None = "6ac56aaceb5c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shipping_areas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("country", sa.String(length=3), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_shipping_areas_code"), "shipping_areas", ["code"], unique=True
    )
    op.create_table(
        "postcode_areas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("area_id", sa.Integer(), nullable=False),
        sa.Column("prefix", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["area_id"],
            ["shipping_areas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("area_id", "prefix"),
    )
    op.create_index(
        op.f("ix_postcode_areas_prefix"), "postcode_areas", ["prefix"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_postcode_areas_prefix"), table_name="postcode_areas")
    op.drop_table("postcode_areas")
    op.drop_index(op.f("ix_shipping_areas_code"), table_name="shipping_areas")
    op.drop_table("shipping_areas")
    # ### end Alembic commands ###
