"""Add manifest code sequence and Manifest.code

Revision ID: 2ee09eaf8a29
Revises: d1ecb9565af3
Create Date: 2026-07-17 14:18:51.422782

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ee09eaf8a29"
down_revision: str | Sequence[str] | None = "d1ecb9565af3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "manifest_codes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("manifests", sa.Column("code", sa.String(length=32), nullable=True))
    op.create_index(op.f("ix_manifests_code"), "manifests", ["code"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_manifests_code"), table_name="manifests")
    op.drop_column("manifests", "code")
    op.drop_table("manifest_codes")
    # ### end Alembic commands ###
