"""carrier number sequences

Revision ID: 378dd6182211
Revises: b77a4afd428c
Create Date: 2026-07-12 23:32:33.924483

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "378dd6182211"
down_revision: str | Sequence[str] | None = "da02ffea2227"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "carrier_number_sequences",
        sa.Column("carrier", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("next_value", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("carrier", "name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("carrier_number_sequences")
    # ### end Alembic commands ###
