"""service groups catalogue and consignment accepted groups

Revision ID: 45d59f0a987e
Revises: 7d481dc1ce8a
Create Date: 2026-07-16 23:22:40.593024

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "45d59f0a987e"
down_revision: str | Sequence[str] | None = "7d481dc1ce8a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service_groups",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.PrimaryKeyConstraint("code"),
    )
    # Server default backfills existing rows with an empty group set (JSON orders
    # carry none); new rows get their value from the app's default=list.
    op.add_column(
        "consignments",
        sa.Column(
            "accepted_service_groups",
            sa.JSON(),
            nullable=False,
            server_default=sa.text("'[]'"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("consignments", "accepted_service_groups")
    op.drop_table("service_groups")
    # ### end Alembic commands ###
