"""phase 1 baseline: consignments, parcels, order events, rulebook versions

Revision ID: 6ac56aaceb5c
Revises:
Create Date: 2026-07-12 16:30:31.596451

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6ac56aaceb5c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "consignments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_number", sa.String(length=64), nullable=False),
        sa.Column("recipient_name", sa.String(length=255), nullable=False),
        sa.Column("address_lines", sa.JSON(), nullable=False),
        sa.Column("postcode", sa.String(length=32), nullable=False),
        sa.Column("destination_country", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("carrier", sa.String(length=64), nullable=True),
        sa.Column("service", sa.String(length=64), nullable=True),
        sa.Column("allocation", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_consignments_order_number"),
        "consignments",
        ["order_number"],
        unique=True,
    )
    op.create_table(
        "order_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_number", sa.String(length=64), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_events_order_number"),
        "order_events",
        ["order_number"],
        unique=False,
    )
    op.create_table(
        "rulebook_versions",
        sa.Column("version", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("author", sa.String(length=64), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("version"),
    )
    op.create_table(
        "parcels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("consignment_id", sa.Integer(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("weight_kg", sa.String(length=16), nullable=False),
        sa.Column("barcode", sa.String(length=80), nullable=False),
        sa.ForeignKeyConstraint(
            ["consignment_id"],
            ["consignments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("consignment_id", "sequence"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("parcels")
    op.drop_table("rulebook_versions")
    op.drop_index(op.f("ix_order_events_order_number"), table_name="order_events")
    op.drop_table("order_events")
    op.drop_index(op.f("ix_consignments_order_number"), table_name="consignments")
    op.drop_table("consignments")
    # ### end Alembic commands ###
