"""consignment records the bought proposition

Revision ID: 9ee5e6bb66b4
Revises: 42d22f45731a
Create Date: 2026-07-12 17:54:14.187083

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9ee5e6bb66b4"
down_revision: str | Sequence[str] | None = "42d22f45731a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "consignments", sa.Column("proposition", sa.String(length=64), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("consignments", "proposition")
    # ### end Alembic commands ###
