"""Add warehouse timezone

Revision ID: a04754d2f808
Revises: 2ee09eaf8a29
Create Date: 2026-07-17 22:08:34.476700

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a04754d2f808"
down_revision: str | Sequence[str] | None = "2ee09eaf8a29"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Backfills existing rows to UTC; the API is the real gate (requires and
    # validates an explicit zone) - this default only covers a bypassing insert.
    op.add_column(
        "warehouses",
        sa.Column(
            "timezone", sa.String(length=64), nullable=False, server_default="UTC"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("warehouses", "timezone")
    # ### end Alembic commands ###
