"""carrier definition versions and carrier configs

Revision ID: b77a4afd428c
Revises: 9ee5e6bb66b4
Create Date: 2026-07-12 22:43:05.767055

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b77a4afd428c"
down_revision: str | Sequence[str] | None = "9ee5e6bb66b4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "carrier_configs",
        sa.Column("carrier", sa.String(length=64), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("carrier"),
    )
    op.create_table(
        "carrier_definition_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("carrier", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("author", sa.String(length=64), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("carrier", "version"),
    )
    op.create_index(
        op.f("ix_carrier_definition_versions_carrier"),
        "carrier_definition_versions",
        ["carrier"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_carrier_definition_versions_carrier"),
        table_name="carrier_definition_versions",
    )
    op.drop_table("carrier_definition_versions")
    op.drop_table("carrier_configs")
    # ### end Alembic commands ###
