"""consignment max dimension

Revision ID: d1ecb9565af3
Revises: 45d59f0a987e
Create Date: 2026-07-16 23:52:08.524853

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d1ecb9565af3"
down_revision: str | Sequence[str] | None = "45d59f0a987e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "consignments",
        sa.Column("max_dimension_cm", sa.String(length=16), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("consignments", "max_dimension_cm")
    # ### end Alembic commands ###
