"""carrier traffic, tracking reference, carrier barcodes

Revision ID: da02ffea2227
Revises: b77a4afd428c
Create Date: 2026-07-12 23:30:45.076722

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da02ffea2227"
down_revision: str | Sequence[str] | None = "b77a4afd428c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "carrier_traffic",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("carrier", sa.String(length=64), nullable=False),
        sa.Column("order_number", sa.String(length=64), nullable=False),
        sa.Column("step", sa.String(length=64), nullable=False),
        sa.Column("request", sa.JSON(), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_body", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_carrier_traffic_carrier"), "carrier_traffic", ["carrier"], unique=False
    )
    op.create_index(
        op.f("ix_carrier_traffic_order_number"),
        "carrier_traffic",
        ["order_number"],
        unique=False,
    )
    op.add_column(
        "consignments",
        sa.Column("tracking_reference", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "parcels", sa.Column("carrier_barcode", sa.String(length=80), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("parcels", "carrier_barcode")
    op.drop_column("consignments", "tracking_reference")
    op.drop_index(op.f("ix_carrier_traffic_order_number"), table_name="carrier_traffic")
    op.drop_index(op.f("ix_carrier_traffic_carrier"), table_name="carrier_traffic")
    op.drop_table("carrier_traffic")
    # ### end Alembic commands ###
